### ISSUE TITLE
how to have external connectivity?

### ISSUE THREAD

**Issue by mlkmhd** [vectorizedio/helm-charts#34]
I googled about how to have an external access to redpanda from out side of kubernetes cluster and I found this documentation:
[https://vectorized.io/docs/kubernetes-external-connect/](url)

but it does not work for me because it's old. currently I'm using version `1.0.6` of redpanda helm chart. 

how can I have an external access from outside of cluster with latest helm chart version?

**Comment by senior7515** [comment]
@mlkmhd  - this repo is deprecated. did you see this: https://vectorized.io/docs on k8s ?

**Comment by senior7515** [comment]
happy to keep the discussion going, but can you open it up on the main redpanda repo as a github discussion
